DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS challenge;
DROP TABLE IF EXISTS solved;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	score INTEGER NOT NULL
);

CREATE TABLE challenge (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	body TEXT NOT NULL,
	score INTEGER NOT NULL
);

CREATE TABLE solved (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	solver_id INTEGER NOT NULL,
	chall_id INTEGER NOT NULL
);
